PRODUCTION_URL = 'https://minesweeper-jd.herokuapp.com'
STAGE_URL = 'https://minesweeper-jd.herokuapp.com'
PRODUCTION_ENV_KEY = 'PROD'
STAGE_ENV_KEY = 'STAGE'
AUTHORIZATION_HEADER_KEY = 'Authorization'
